title: Core Digital Studio
description: Workflow Autopilot insights and automation notes
url: https://yourusername.github.io
baseurl: "" # leave empty for root
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /blog/:title/
